views/login.py
from flask import request, session, g, redirect, url_for, abort, \
     render_template, flash, Blueprint
from time import sleep, time
import random
from users.models import User
from users.views.password import getPasswordHash, matchPasswordToHash
from users.utils import get_access_token
from users.admin import silent_login

mod = Blueprint('login',__name__, template_folder='../templates')


def setExits():
    g.title = 'Login'
    g.loginURL = url_for('.login')
    g.recoverURL = url_for('.recover_password')
    g.logoutURL = url_for('.logout')
    g.registerURL = url_for('user.register')
    
@mod.route('/login', methods=['POST', 'GET'])
@mod.route('/login/', methods=['POST', 'GET'])
def login():
    setExits()
    g.user = g.get('user',None)
    next = request.args.get('next',request.form.get('next',''))
    
    if g.user is not None:
        #flash("Already Logged in...")
        return redirect('/')
        
    if 'reset' in request.args:
        #Try to find the user record that requested a reset
        rec=User(g.db).select_one(where='access_token = "{}"'.format(request.args.get('reset','')).strip())
        if rec and rec.access_token_expires > time():
            userNameOrEmail=rec.username
            if not userNameOrEmail:
                userNameOrEmail=rec.email
            setUserStatus(userNameOrEmail,rec.id)
            return redirect(url_for('user.edit'))
        else:
            flash("That reset request has expired")
            return redirect('/')
            
    if not request.form:
        if 'loginTries' not in session:
            session['loginTries'] = 0
        
    if request.form:
        if 'loginTries' not in session:
            #Testing that user agent is keeping cookies.
            #If not, there is no point in going on... Also, could be a bot.
            return render_template('login/no-cookies.html')
        
        result = authenticate_user(request.form["userNameOrEmail"],request.form['password'])
        if result != 0:
            session['loginTries'] = 0
            if result == -1:
                flash("Your account is inactive")
                return render_template('/login/inactive.html')
            #import pdb;pdb.set_trace()          
            if next:
                return redirect(next)
            return redirect('/') #logged in...
        else:
            flash("Invalid User Name or Password")
        
    if 'loginTries' not in session:
        session['loginTries'] = 0
        
    #remember howmany times the user has tried to log in
    session['loginTries'] = session['loginTries'] + 1
    #slow down login attempts
    if session['loginTries'] > 5:
        sleep(session['loginTries']/.8)
        
    return render_template('login/login.html', form=request.form, next=next)
       
    
@mod.route('/logout', methods=['GET'])
@mod.route('/logout/', methods=['GET'])
def logout():
    session.clear()
    g.user = None
    flash("Successfully Logged Out")
    return redirect('/')
    
@mod.route('/reset', methods=['GET','POST'])
@mod.route('/reset/', methods=['GET','POST'])
def recover_password():
    """Send reset password and send user an email if they forget their password"""
    
    setExits()
    g.title = "Reset Password"
    rec=None
    temp_pass = None
    email_not_found = False
    
    if not request.form:
        pass
    else:
        #find the user with that email
        rec = User(g.db).select_one(where='email = "{}"'.format(request.form['email'].strip()))
        if rec == None:
            flash("That email address could not be found in the list of users.")
        else:
            # generate a new password that is unique to the system
            temp_pass = get_access_token()
            # save the temporary password
            rec.access_token = temp_pass
            rec.access_token_expires = time() + (3600 * 48) # 2 days to reset
            User(g.db).save(rec)
            g.db.commit()
            
            # send an email with instructions
            from takeabeltof.mailer import send_message
            full_name = rec.first_name + " " + rec.last_name
            context = {'temp_pass':temp_pass,'rec':rec,'full_name':full_name}
            to_address_list=[(full_name,rec.email),]
            result,msg = send_message(
                to_address_list,
                context=context,
                html_template='login/email/confirm_reset.html',
                text_template='login/email/confirm_reset.txt',
                subject = 'Confirm Password Reset'
                )
    
    # Return a page telling user what we did
    return render_template('login/recover_password.html',temp_pass=temp_pass,rec=rec)
    
    
@mod.route('/quiet_test', methods=['GET','POST'])
@mod.route('/quiet_test/', methods=['GET','POST'])
@silent_login()
def quite_test_fixture():
    """Simple way to test that the silent_login decorator is working"""
    return "Ok"
    
    
def setUserStatus(userNameOrEmail,user_id):
    #Log the user in
    user = User(g.db)
    user.update_last_access(user_id)
    session["user"] = userNameOrEmail.strip()
    g.user = session["user"]
    session["user_roles"] = []
    recs = user.get_roles(user_id)
    if recs:
        session["user_roles"] = [rec.name for rec in recs]
    g.user_roles = session['user_roles']
    
    
def authenticate_user(username,password,**kwargs):
    """
    Check username and password in db and return:
        0 = Authentication Failed
        1 = Authentication Succeeded
        -1 = User Inactive
        
    Optional kwargs:
        include_inactive = True
        login_on_success = True
    """
    
    include_inactive = kwargs.get('include_inactive',True)
    login_on_success = kwargs.get('login_on_success',True)
    
    result = 0
    
    rec = User(g.db).get(username,include_inactive=include_inactive)

    if rec and matchPasswordToHash(password,rec.password):
        result = 1
        if rec.active != 1:
            result = -1
        if rec.active == 1 and login_on_success:
            setUserStatus(username,rec.id)
            
    return result
            

    
    

views/user.py
from datetime import datetime
from flask import request, session, g, redirect, url_for, abort, \
     render_template, flash, Blueprint
from takeabeltof.utils import printException, cleanRecordID, looksLikeEmailAddress, render_markdown_for
from time import time
from users.models import User, Role
from users.utils import get_access_token
from users.views.login import setUserStatus
from users.views.password import getPasswordHash
from users.admin import login_required, table_access_required


mod = Blueprint('user',__name__, template_folder='../templates', url_prefix='/user')


def setExits():
    g.listURL = url_for('.display')
    g.adminURL = url_for('.admin',id=0)
    g.editURL = url_for('.edit')
    g.registerURL = url_for('.register')
    g.deleteURL = url_for('.delete')
    g.homeURL = url_for('.home')
    g.title = 'User'

@mod.route('/')
@login_required
def home():
    setExits()
    return render_template('user/user_index.html')
    
@mod.route('/list/', methods=['GET'])
@table_access_required(User)
def display():
    setExits()
    g.title = "{} List".format(g.title)
    include_inactive = True
    
    recs = User(g.db).select(include_inactive=include_inactive)
    return render_template('user/user_list.html', recs=recs)
    
@mod.route('/edit/<int:id>/', methods=['POST','GET'])
@table_access_required(User)
def admin(id=None):
    """Administrator access for the User table records
    """
    setExits()
    if id == None:
        flash("No User identifier supplied")
        return redirect(g.listURL)
        
    #import pdb;pdb.set_trace()
        
    id = cleanRecordID(id)
    if(id < 0):
        flash("That is an invalid id")
        return redirect(g.listURL)
        
    #session['user_edit_token'] = id
    
    return edit(id)
    

## Edit the user
@mod.route('/edit', methods=['POST', 'GET'])
@mod.route('/edit/', methods=['POST', 'GET'])
@login_required
def edit(rec_handle=None):
    setExits()
    g.title = "Edit {} Record".format(g.title)
    #import pdb;pdb.set_trace()

    user = User(g.db)
    rec = None
    request_rec_id = cleanRecordID(request.form.get('id',request.args.get('id',-1)))
    is_admin = g.admin.has_access(g.user,User)
    no_delete = not is_admin
    session_roles = session["user_roles"] #roles of currnet user
    new_password = ''
    confirm_password = ''
    user_roles = ['user'] # default
    roles = Role(g.db).select()
    include_inactive = True
    
    if not is_admin:
        g.listURL = g.homeURL # Non admins can't see the list
        include_inactive = False
        
    if rec_handle != None:
        pass #rec_handle has to come from admin() at this point
    elif rec_handle == None and g.user != None and request_rec_id == -1:
        rec_handle = g.user
    else:
        rec_handle = request_rec_id
        if rec_handle < 0:
            flash("That is not a valid User ID")
            return redirect(g.listURL)
        
    if not request.form:
        """ if no form object, send the form page """
        if rec_handle != g.user and not is_admin:
            flash("You do not have access to that area")
            return redirect(g.homeURL)
        elif rec_handle == 0:
            rec = user.new()
        else:
            rec = user.get(rec_handle,include_inactive=include_inactive)
            if not rec:
                flash("Unable to locate user record")
                return redirect('/')
                
            user_roles = get_user_role_names(rec)
        
    else:
        #have the request form
        #import pdb;pdb.set_trace()
        is_new_user = False
        if rec_handle and request.form['id'] != 'None':
            rec = user.get(rec_handle,include_inactive=include_inactive)
            user_roles = get_user_role_names(rec)
        else:
            # its a new unsaved record
            is_new_user = True
            rec = user.new()
            user.update(rec,request.form)

        if validForm(rec):
        
            #Are we editing the current user's record?
            editingCurrentUser = ''
            if(g.user == rec.username):
                if 'new_username' in request.form:
                    editingCurrentUser = request.form['new_username'].strip()
                else:
                    editingCurrentUser = g.user
            else: 
                if(g.user == rec.email):
                    editingCurrentUser = request.form['email'].strip()
            
            #update the record
            user.update(rec,request.form)
            
            set_username_from_form(rec)        
            set_password_from_form(rec)
    
            try:
                user.save(rec)
                
                # update the user roles
                if 'roles_select' in request.form:
                    #delete all the users current roles
                    user.clear_roles(rec.id)
                    for role_name in request.form.getlist('roles_select'):
                        #find the role by name
                        role = Role(g.db).select_one(where='name = "{}"'.format(role_name))
                        if role:
                            user.add_role(rec.id,role.id)
                    
                # if the username or email address are the same as g.user
                # update g.user if it changes
                if(editingCurrentUser != ''):
                    setUserStatus(editingCurrentUser,rec.id)
                    
                g.db.commit()
                
            except Exception as e:
                g.db.rollback()
                flash(printException('Error attempting to save '+g.title+' record.',"error",e))
                return redirect(g.listURL)
                
            if is_new_user == True and rec.email:
                from takeabeltof.mailer import send_message
                
                # send an email to welcome the new user
                full_name = '{} {}'.format(rec.first_name,rec.last_name).strip()
                
                context = {'rec':rec,'full_name':full_name,}
                to_address_list=[(full_name,rec.email)]
                sent,msg = send_message(
                    to_address_list,
                    subject="Welcome to {{config.SITE_NAME}}",
                    context=context,
                    html_template='user/email/welcome.html',
                    text_template='user/email/welcome.txt',
                    )
                if not sent:
                    flash('The welcome message could not be sent. Error: {}'.format(msg))
                    
            return redirect(g.listURL)
        
        else:
            # form did not validate, give user the option to keep their old password if there was one
            #need to restore the username
            user.update(rec,request.form)
            if 'new_username' in request.form:
                rec.username = request.form['new_username'] #preserve user input
            # preserve the selected roles
            #import pdb;pdb.set_trace()
            if 'roles_select' in request.form:
                user_roles = request.form.getlist('roles_select')
            #and password
            new_password = request.form.get('new_password','')
            confirm_password = request.form.get('confirm_password','')

    # display form
    return render_template('user/user_edit.html', rec=rec, 
        no_delete=no_delete, 
        is_admin=is_admin, 
        user_roles=user_roles, 
        roles=roles,
        session_roles=session_roles,
        new_password=new_password,
        confirm_password=confirm_password,
        )
    
@mod.route('/register', methods=['GET','POST',])
@mod.route('/register/', methods=['GET','POST',])
def register():
    """Allow people to sign up thier own accounts on the web site"""
    setExits()
    g.title = "Account Registration"
    g.editURL = url_for('.register')
    g.listURL = '/' # incase user cancels
    user = User(g.db)
    rec=user.new()
    
    from takeabeltof.mailer import send_message
    from app import app
    
    is_admin = False
    user_roles=None
    roles=None
    no_delete=True
    success=True
    help = render_markdown_for("user/new_account_help.md",mod)        
    
    if 'confirm' in request.args:
        #Try to find the user record that requested registration
        rec=user.select_one(where='access_token = "{}"'.format(request.args.get('confirm','')).strip())
        if rec and rec.access_token_expires > time():
            if rec.active == 1:
                success="active"
            else:
                success="waiting"
                
            #inform the admin
            to=[(app.config['MAIL_DEFAULT_SENDER'],app.config['MAIL_DEFAULT_ADDR'])]
            confirmURL = "{}://{}{}?activate={}".format(app.config['HOST_PROTOCOL'],app.config['HOST_NAME'],url_for('.activate'), rec.access_token)
            deleteURL = "{}://{}{}?delete={}".format(app.config['HOST_PROTOCOL'],app.config['HOST_NAME'],url_for('.delete'), rec.access_token)
            context={'rec':rec,'confirmURL':confirmURL,'deleteURL':deleteURL}
            subject = 'Activate Account Request from - {}'.format(app.config['SITE_NAME'])
            html_template = 'user/email/admin_activate_acct.html'
            text_template = None
            send_message(to,context=context,subject=subject,html_template=html_template,text_template=text_template)
            
            return render_template('user/registration_success.html',success=success)
        else:
            flash("That registration request has expired")
            return redirect('/')

    if not request.form:
        pass
    else:
        if validForm(rec):
            #update the record
            user.update(rec,request.form)
            rec.active = 0 # Self registered accounts are inactive by default
            set_password_from_form(rec)
            set_username_from_form(rec)
            rec.access_token = get_access_token()

templates/user/registration_success.html
{% extends "layout.html" %}
{% block title %}{{ g.title }}{% endblock %}
{% block body %}
<div class="w3-container">
    <div class="w3-col m1 l2">&nbsp;</div>
    <div class="entry w3-col w3-panel w3-card-4 l8 m10 ">
{% if success == 'active' %}
    <h3>Your account is now active.</h3>
    <p>Your account is now ready to use. You may <a href="{{url_for('login.login')}}">log in</a> here.</p>
{% elif success == 'waiting' %}
    <h3>Your account is awaiting activation</h3>
    <p>Thank you for confirming your email address. Your account is now awaiting activation by the site administrator. This should be completed within a day or so.</p>
    <p>We will contact you at the email address you provided. If you have questions please feel free to <a href="/contact/">contact us</a>.</p>
{% elif success %}
    <h3>Signup Successful</h3>
    <p>Thank you for creating an account at {{config.SITE_NAME}}.</p>
    <p>An email has been sent to the email address you provided. In order to activate your account you must follow the link provided there to confirm your email address.</p>
    <p>Your account will then be activated by the site administrator.</p>
{% else %}
    <h3>There was a problem with your signup</h3>
    <p>We're sorry, but there was an error encountered while attempting to create your account. The site adminstrator has been notified.</p>
    <p>We will contact you at the email address you provided. If you have questions please feel free to <a href="/contact/">contact us</a>.</p>
{% endif %}

    <p><a href="/">Go to Site home page</a></p>
    
    </div>
</div>
{% endblock body %}

templates/user/user_edit.html
{% extends "form_layout.html" %}

{% from "_form_helpers.html" import input_field, select_field, radio_field, checkbox_field, label_only %}

{% block fieldset %}
<fieldset>
    <p>{{ input_field(rec.id,"id",type="hidden",default=0) }}</p>
    <p>{{ input_field(rec.first_name,"first_name",label="First Name*",req=True) }}</p>
    <p>{{ input_field(rec.last_name,"last_name",label="Last Name*",req=True) }}</p>
    <p>{{ input_field(rec.email,"email",label="Email*",req=True, type="email") }}

    {% set extras = "" %}
    {% if not config.ALLOW_USERNAME_CHANGE %}{% set extras = 'disabled="disabled"' %}{% endif %}
    <p>{{ input_field(rec.username,"new_username",label="User Name",extras=extras) }}
    
    {% set label = 'Password <em class="w3-small">(&mdash; Optional &mdash;)</em>' %}
    {% if rec.password and rec.password != '' %}
        {% set label = 'Password <em class="w3-small">(leave as-is to keep current)</em>' %}
    {% endif %}
    <p>{{ input_field(new_password,"new_password",type="password",label=label) }}</p>
    <p>{{ input_field(confirm_password,"confirm_password",type="password",label="Re-enter password") }}</p>
    <p>{{ input_field(rec.address,"address") }}</p>
    <p>{{ input_field(rec.address2,"address2",label="Address line 2") }}</p>
    <p>{{ input_field(rec.city,"city") }}</p>
    <p>{{ input_field(rec.state,"state") }}</p>
    <p>{{ input_field(rec.zip,"zip") }}</p>
    <p>{{ input_field(rec.phone,"phone") }}</p>
    
    {% if is_admin %}
    <p>{{ select_field("roles_select","Role",extras='multiple size="5"', class="w3-border") }}
            {% for role in roles %}
                {% if role.name == "super" and "super" is not in session_roles %}
                {% else %}
                <option value="{{role.name}}" {% if role.name in user_roles %}selected="selected" {% endif %}>{{role.name}}</option>
                {% endif %}
            {% endfor %}
        </select>
        </p>
        <p>
            {% set extras = "" %}
            {% if rec.active ==1 %}{% set extras = ' checked="checked"' %}{% endif %}
            {{ radio_field(1,"active","Active:",extras=extras ,right=True) }}&nbsp;
            {% set extras = "" %}
            {% if rec.active ==0 %}{% set extras = ' checked="checked"' %}{% endif %}
            {{ radio_field(0,"active","Inactive:",extras=extras ,right=True ) }}
        </p>
        <p>{{ label_only("Last Access:")}} {{rec.last_access|default('Never',True)}} (UTC)</p>
    {% endif %}
</fieldset>
{% endblock %}

templates/user/user_index.html
{% extends "layout.html" %}
{% block title %}User Profile{% endblock %}
{% block body %}
    {% if g.user %}
       <h3>User Profile for {{ g.user }}</h3>
    {% else %}
        <h3>You must be logged in to see more...</h3>
    {% endif %}
    <ul class="list-menu">
        {% if g.user %}
        <li><a href="{{ url_for('user.edit')}}" >Manage Your User Record</li>
        <li><a href="{{ url_for('login.logout')}}">Logout</a></li>
        {% else %}
        <li><a href="{{ url_for('login.login')}}" >Login</li>
        {% endif %}
    </ul>
{% endblock %}

templates/user/user_list.html
{% extends "layout.html" %}
{% block title %}{{ g.title }}{% endblock %}
{% block body %}
  	<p id="addRecord"><a href="{{ g.adminURL }}">Add a new record</a></p>
	{%if recs %}
		<table class="datatable w3-table w3-hoverable">
		<tr  class="w3-primary-color">
			<th>Id</th>
			<th>Name</th>
			<th class="w3-hide-small">Email</th>
			<th>Status</th>
		</tr>
		{% for rec in recs %}
	    <tr>
			<td onclick="window.location='{{ g.editURL }}{{rec.id}}/'">{{ rec.id }}</td>
			<td onclick="window.location='{{ g.editURL }}{{rec.id}}/'">{{ rec.first_name }} {{ rec.last_name}}</td>
			<td onclick="window.location='{{ g.editURL }}{{rec.id}}/'" class="w3-hide-small">{{ rec.email|default("",true) }}</td>
			<td onclick="window.location='{{ g.editURL }}{{rec.id}}/'">{% if rec.active == 1 %}Active{% else %}<em>Inactive</em>{% endif %}</td>
		</tr>
		{% endfor %}
	  </table>
  	{% else %}
    	<p><em>No records here so far</em></p>
	{% endif %}
{% endblock %}